name: Build and Push Docker Image
on:
  push:
    branches: [ main, staging ]

env:
  GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

#      - name: Login to Private Docker Registry
#        uses: docker/login-action@v3
#        with:
#          registry: registry.hyperindiv.com
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: registry.hyperindiv.com/chatgpt-retrieval-plugin:latest

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REPO_GITHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/guiramos/chatgpt-retrieval-plugin:latest

      - name : Create tag and release
        id : create_release
        uses : actions/create-release@latest
        with :
          tag_name : v${{ github.run_number }}
          release_name : Release ${{ github.run_number }}
          draft : false
          prerelease : false
      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INDIV_HOST }}
          username: ${{ secrets.INDIV_USER }}
          key: ${{ secrets.INDIV_SSH_KEY }}
          script: |
            cd ~/code/images/generic/chatgpt-retrieval-plugin
            git pull
            docker-compose pull
            ./run.sh stop start
            ENDSSH