name: Build and Push Docker Image
on:
  push:
    branches: [ main, staging ]

env:
  GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Private Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.hyperindiv.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.hyperindiv.com/chatgpt-retrieval-plugin:latest

      - name : Create tag and release
        id : create_release
        uses : actions/create-release@latest
        with :
          tag_name : ${{ steps.tag_action.outputs.tag }}
          release_name : ${{ steps.tag_action.outputs.tag }}
          draft : false
          prerelease : false
